import Link from 'next/link';
import {contacts,navigation,pending,processSteps,recruiters,statistics} from '@/data/site';
export function PhotoPlaceholder({title='Guru Nanak Dev University',caption='Approved campus photography will appear here.',label='THE CAMPUS'}:{title?:string;caption?:string;label?:string}){return <figure className="photo-placeholder"><div className="photo-label"><span>{label}</span><span>PHOTOGRAPH TO BE SUPPLIED</span></div><div className="photo-center">{title}<small>{caption}</small></div><figcaption>Guru Nanak Dev University<small>Amritsar, Punjab, India</small></figcaption></figure>}
export function PageHero({eyebrow,title,description}:{eyebrow:string;title:string;description:string}){return <section className="page-hero wrap"><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p className="intro">{description}</p></section>}
export function SectionTitle({label,title,description}:{label:string;title:string;description?:string}){return <div className="section-heading"><div><div className="eyebrow">{label}</div><h2>{title}</h2></div>{description&&<p>{description}</p>}</div>}
export function Statistics(){return <section className="section wrap"><SectionTitle label="THE ENGINEERING ECOSYSTEM" title="GNDU engineering at a glance." description="Verified university figures will be published following official review."/><div className="stats">{statistics.map(s=><div key={s.label}><strong>{s.value===null?'—':s.value+'+'}</strong><span>{s.label}</span><small>{s.value===null?'Data awaiting verification':''}</small></div>)}</div></section>}
export function RecruiterGrid(){return recruiters.length?<div className="recruiter-grid">{recruiters.map(r=><div key={r.name}><img src={r.logo} alt={r.name} width={160} height={65} loading="lazy"/></div>)}</div>:<div className="recruiter-grid">{Array.from({length:6},(_,i)=><div key={i}><span>RECRUITER {String(i+1).padStart(2,'0')}</span><small>Verified name & logo pending</small></div>)}</div>}
export function Process(){return <div className="process">{processSteps.map((s,i)=><div key={s.title}><span className="step-number">{String(i+1).padStart(2,'0')}</span><h3>{s.title}</h3><p>{s.description}</p></div>)}</div>}
export function FinalCTA(){return <section className="recruit-banner"><div className="wrap"><div className="eyebrow">BUILD A CAMPUS PARTNERSHIP</div><h2>Bring your next campus<br/>recruitment drive to GNDU.</h2><p>Connect with the university placement team to discuss graduate hiring, internships, technical assessments and campus engagement.</p><div className="actions"><Link className="button light" href="/recruit">Submit Recruitment Request <span>↗</span></Link><Link className="text-link" href="/placement-cell#contact">Contact Placement Cell →</Link></div></div></section>}
export function Contact(){return <section className="wrap section" id="contact"><SectionTitle label="CONTACT US" title="Directorate of Placement & Career Enhancement"/><div className="contact-grid"><div><h3>Address</h3><p>Guru Nanak Dev University<br/>G.T. Road, Amritsar – 143005<br/>Punjab, India</p><a className="text-link" href="https://www.google.com/maps/search/?api=1&query=Guru+Nanak+Dev+University+Amritsar" target="_blank" rel="noopener noreferrer">Get Directions ↗</a></div><dl><dt>Placement enquiries</dt><dd><a href="tel:+911832257674">0183-2257674</a></dd><dt>Email</dt><dd><a href="mailto:placement@gndu.ac.in">placement@gndu.ac.in</a></dd><dt>PABX</dt><dd>0183-2258802–09 (Extn. 3172)</dd><dt>Fax</dt><dd>0183-2258819/20</dd></dl><div><h3>General enquiries</h3><p>0183-2258802–09</p><p>For other enquiries, please visit the university website.</p><a className="text-link" href="https://www.gndu.ac.in/" target="_blank" rel="noopener noreferrer">www.gndu.ac.in ↗</a></div></div></section>}
export function Footer(){return <footer className="site-footer"><div className="wrap footer-grid"><div><h3 className="footer-brand">Guru Nanak Dev<br/>University</h3><p>Corporate Recruitment & Talent<br/>Amritsar, Punjab, India</p><a href="https://www.gndu.ac.in/" target="_blank" rel="noopener noreferrer">University website ↗</a></div><div><h4>Talent & Innovation</h4>{navigation.slice(1,4).map(n=><Link key={n.href} href={n.href}>{n.label}</Link>)}</div><div><h4>For Recruiters</h4><Link href="/recruiters">Industry Network</Link><Link href="/why-gndu">Why GNDU</Link><Link href="/recruit">Recruit From GNDU</Link></div><div><h4>Resources</h4><Link href="/placement-policy">Placement Policy</Link><Link href="/privacy">Privacy</Link><Link href="/accessibility">Accessibility</Link></div><div><h4>Contact</h4><Link href="/placement-cell">Placement Cell</Link><Link href="/placement-cell#contact">Corporate Relations</Link><span>Official details pending</span></div></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} Guru Nanak Dev University, Amritsar</span><span>Recruitment information is subject to official university policies.<br/>Draft portal · Pending official content verification.</span></div></footer>}

