const technologies=[
 ['01','AI & intelligent systems','Learning to build, evaluate and use intelligent systems responsibly.',['Generative AI','AI agents','RAG & vector databases','Machine learning','Computer vision']],
 ['02','Cloud & DevOps','Developing skills in scalable infrastructure and reliable software delivery.',['AWS','Microsoft Azure','Google Cloud','Docker & Kubernetes','CI/CD & serverless']],
 ['03','Data & analytics','Working with data to discover patterns and support informed decisions.',['Python & SQL','Data engineering','Apache Spark','Power BI','Real-time analytics']],
 ['04','Cybersecurity','Understanding how to protect applications, networks and digital identities.',['Cloud security','Secure coding','Threat detection','Identity & access','Ethical hacking']],
 ['05','Software engineering','Building fluency across modern web, mobile and backend technologies.',['React & Next.js','TypeScript','APIs & microservices','Flutter','Software testing']],
 ['06','Connected & emerging systems','Exploring the intersection of software, devices and intelligent computing.',['Internet of Things','Embedded systems','Edge AI','Robotics','AR / VR']]
] as const;
export function TechnologyShowcase(){return <section className="technology-showcase"><div className="wrap section"><div className="tech-intro"><div className="eyebrow">OUR STUDENTS · OUR TECHNOLOGIES</div><h2>Skills across a changing<br/>technology landscape.</h2><p>GNDU students work across diverse technologies, developing technical knowledge through hands-on learning, practice and collaboration.</p></div><div className="technology-card-grid">{technologies.map(([number,title,description,tags])=><article className="technology-skill-card" key={title}><span className="tech-number">{number}</span><h3>{title}</h3><p>{description}</p><div className="technology-tags">{tags.map(tag=><span key={tag}>{tag}</span>)}</div></article>)}</div></div></section>}
const providers=[['Google','google'],['Microsoft','microsoft'],['AWS','amazonwebservices'],['HackerRank','hackerrank'],['Coursera','coursera'],['Harvard','harvard'],['GitHub','github'],['Microsoft Azure','azure'],['IBM','ibm'],['Cisco','cisco'],['Oracle','oracle'],['NVIDIA','nvidia'],['Salesforce','salesforce'],['Red Hat','redhat'],['MongoDB','mongodb'],['Databricks','databricks'],['Snowflake','snowflake'],['SAP','sap'],['Palo Alto Networks','paloaltonetworks'],['Fortinet','fortinet']];
export function Certifications(){return <section className="wrap section certification-section"><div className="eyebrow">CONTINUOUS LEARNING</div><h2>Learning backed by recognised credentials.</h2><p className="certification-intro">Our students complement university learning with certifications and course certificates from technology companies, learning platforms and universities.</p><div className="certification-grid">{providers.map(([name,file])=><div className="certification-brand" key={name}><img src={'/images/certifications/'+file+'.svg'} alt={name} width={130} height={60} loading="lazy"/><span>{name}</span></div>)}</div></section>}
